FROM nginx:1.24.0-bullseye as nginx

FROM phpdockerio/php:7.4-fpm
#FROM php:7.4.33-fpm-bullseye

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    php7.4-memcached \
    php7.4-memcache \
    php7.4-mbstring \
    php7.4-mysqli \
    php7.4-intl \
    php7.4-xdebug \
    php7.4-interbase \
    php7.4-soap \
    php7.4-gd \
    php7.4-imagick \
    php7.4-opcache \
    php7.4-zip \
    php-pear php7.4-dev libmcrypt-dev gcc make autoconf libc-dev pkg-config \
    && pecl install mcrypt-1.0.4 \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./images/php-bx/php.ini /etc/php/7.4/fpm/conf.d/90-php.ini
COPY ./images/php-bx/php.ini /etc/php/7.4/cli/conf.d/90-php.ini

RUN usermod -u 1000 www-data

WORKDIR /var/www/bitrix

EXPOSE 9000

#CMD ["php-fpm"]

COPY --from=nginx /etc/nginx /etc/nginx
COPY --from=nginx /usr/sbin/nginx /usr/sbin/nginx
COPY ./images/php-bx/nginx.conf /etc/nginx/nginx.conf
COPY ./images/php-bx/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir /var/log/nginx
RUN mkdir /var/cache/nginx
RUN mkdir /var/cache/nginx/client_temp

COPY ./images/php-bx/entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
